//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirProduct
    {
        public string Name { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string DepartureDate { get; set; }
        public Nullable<decimal> DepartureTime { get; set; }
        public string ArrivalDate { get; set; }
        public Nullable<decimal> ArrivalTime { get; set; }
        public bool IsSaved { get; set; }
        public bool IsBooked { get; set; }
        public decimal Price { get; set; }
        public int Id { get; set; }
    }
}
